apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea
spec:
  instances: 1
  storage:
    size: 8Gi
    storageClass: freenas-iscsi
  bootstrap:
    initdb:
      database: gitea
      owner: gitea
      secret:
        name: gitea-database-credentials
  managed:
    roles:
      - name: gitea
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: gitea-database-credentials