---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: externaldns-cloudflare
spec:
  chartRef:
    kind: OCIRepository
    name: externaldns-cloudflare
  interval: 30m
  values:
    fullnameOverride: &name externaldns-cloudflare
    logLevel: info
    domainFilters:
      - stanleygrange.uk
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: externaldns-cloudflare-secrets
            key: cloudflare_api_token
    extraArgs:
      - --cloudflare-dns-records-per-page=1000
      - --cloudflare-proxied
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --gateway-name=envoy-external
      - --ingress-class=external-nginx
    podAnnotations:
      secret.reloader.stakater.com/reload: externaldns-cloudflare-secrets
    policy: sync
    provider:
      name: cloudflare
    resources:
      requests:
        cpu: 13m
        memory: 42M
      limits:
        memory: 42M
    serviceMonitor:
      enabled: true
    sources:
      - ingress
      - gateway-httproute
      - crd
    triggerLoopOnEvent: true
    txtOwnerId: fsn1
    txtPrefix: "fsn1."

  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: *name
            patch: |-
              - op: add
                path: /spec/template/spec/enableServiceLinks
                value: false