---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2025.10.0
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 30m
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: secret_key
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-secrets
      valuesKey: psql_password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-secrets
      valuesKey: psql_password
      targetPath: postgresql.auth.password
  values:
    authentik:
      error_reporting:
        enabled: true

    server:
      ingress:
        enabled: true
        hosts:
          - id.stanleygrange.uk

    postgresql:
      enabled: true
      global:
        defaultStorageClass: freenas-iscsi
      primary:
        persistence:
          enabled: true
    redis:
      enabled: true