---
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
clusterName: &clusterName ${K8S_CLUSTER_NAME}
endpoint: "https://${K8S_ENDPOINT_DNS}:6443"

# renovate: depName=ghcr.io/siderolabs/installer datasource=docker
talosVersion: v1.11.3
# renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
kubernetesVersion: v1.34.1

cniConfig:
  name: none

additionalApiServerCertSans: &san
  - ${K8S_ENDPOINT_IP}
  - ${K8S_ENDPOINT_DNS}
  - "127.0.0.1" # KubePrism

additionalMachineCertSans: *san

nodes:
  - hostname: k8s-1.fsn1.stanleygrange.uk
    ipAddress: 172.16.99.11
    controlPlane: true
    installDiskSelector:
      size: ">=32GB"
    networkInterfaces:
      - deviceSelector:
          physical: true
        dhcp: true

  - hostname: k8s-2.fsn1.stanleygrange.uk
    ipAddress: 172.16.99.12
    controlPlane: true
    installDiskSelector:
      size: ">=32GB"
    networkInterfaces:
      - deviceSelector:
          physical: true
        dhcp: true

  - hostname: k8s-3.fsn1.stanleygrange.uk
    ipAddress: 172.16.99.13
    controlPlane: true
    installDiskSelector:
      size: ">=32GB"
    networkInterfaces:
      - deviceSelector:
          physical: true
        dhcp: true

patches:
  # Enable KubePrism
  - |-
    machine:
      features:
        kubePrism:
          enabled: true
          port: 7445
  
  # Disable CPU Frequency throttling
  - |-
    machine:
      install:
        extraKernelArgs:
          - cpufreq.default_governor=performance

  # Disable search domain everywhere
  - |-
    machine:
      network:
        disableSearchDomain: true

  # Custom sysctls
  - |-
    machine:
      sysctls:
        fs.inotify.max_queued_events: "65536"
        fs.inotify.max_user_instances: "8192"
        fs.inotify.max_user_watches: "524288"
        net.core.rmem_max: "2500000"
        net.core.wmem_max: "2500000"

  # Time
  - |-
    machine:
      time:
        disabled: false
        servers:
          - time.cloudflare.com

  # Extra Hosts Entries
  - |-
    machine:
      network:
        extraHostEntries:
          - ip: ${K8S_ENDPOINT_IP}
            aliases:
              - ${K8S_ENDPOINT_DNS}

  # Kubelet configuration
  - |-
    machine:
      kubelet:
        extraArgs:
          rotate-server-certificates: "true"
        extraConfig:
          maxPods: 150
        nodeIP:
          validSubnets:
              - 172.16.99.0/24

  # Configure containerd
  - |-
    machine:
      files:
        - op: create
          path: /etc/cri/conf.d/20-customization.part
          content: |
            [plugins]
              [plugins."io.containerd.grpc.v1.cri"]
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true

  # Subnets
  - |-
    cluster:
      network:
        dnsDomain: cluster.local
        podSubnets:
          - 10.124.0.0/16
        serviceSubnets:
          - 10.96.0.0/12

controlPlane:
  nodeLabels:
    topology.kubernetes.io/region: *clusterName
    topology.kubernetes.io/zone: fsn1

  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=1
      systemExtensions:
        officialExtensions:
          - siderolabs/intel-ucode
          - siderolabs/i915

  patches:
    # Cluster configuration
    - |-
      cluster:
        allowSchedulingOnMasters: true
        proxy:
          disabled: true

    # ETCD configuration
    - |-
      cluster:
        etcd:
          advertisedSubnets:
            - 172.16.99.0/24

    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

    # kube api server resource limits
    - |-
      cluster:
        apiServer:
          resources:
            requests:
              cpu: 5m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 1Gi

    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - system-upgrade
