---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-instance
spec:
  chart:
    spec:
      chart: flux-instance
      version: 0.32.0
      sourceRef:
        kind: HelmRepository
        name: controlplaneio
        namespace: flux-system
  interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: flux-instance-helm-values
