apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak
spec:
  instances: 3
  storage:
    size: 1Gi
    storageClass: freenas-iscsi
  managed:
    roles:
      - name: keycloak
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: keycloak-database-credentials
