---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  chartRef:
    kind: OCIRepository
    name: keycloak
  interval: 30m
  valuesFrom:
    - kind: Secret
      name: keycloak-credentials
      valuesKey: username
      targetPath: keycloak.adminUser
    - kind: Secret
      name: keycloak-credentials
      valuesKey: password
      targetPath: keycloak.adminPassword
    - kind: Secret
      name: keycloak-database-credentials
      valuesKey: username
      targetPath: database.username
    - kind: Secret
      name: keycloak-database-credentials
      valuesKey: password
      targetPath: database.password
  values:
    image:
      registry: docker.io
      repository: keycloak/keycloak
      tag: "26.4.2@sha256:3617b09bb4b7510a8d8d9b9fc5707399e2d70688dbcc2f8fb013a144829be1b9"
      imagePullPolicy: IfNotPresent
      command: "/opt/keycloak/bin/kc.sh"

    replicaCount: 3

    keycloak:
      hostname: id.stanleygrange.uk
      hostnameStrict: true
      httpEnabled: true
      httpPort: 8080
      httpsPort: 8443
      proxyHeaders: "xforwarded"
      proxyProtocolEnabled: false
      proxyTrustedAddresses: ""
      production: true
      httpRelativePath: /
      extraArgs: []

    database:
      type: postgres
      host: keycloak-rw.hosted.svc.cluster.local
      name: keycloak

    cache:
      stack: local
      configFile: ""

    realm:
      import: false

    service:
      type: ClusterIP
      httpPort: 8080
      httpsPort: 8443
      httpTargetPort: 8080
      httpsTargetPort: 8443
      annotations: {}
      trafficDistribution: ""

    ingress:
      enabled: true
      className: external-nginx
      annotations: {}
        
        # nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      hosts:
        - host: id.stanleygrange.uk
          paths:
            - path: /
              pathType: Prefix
      tls: []

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

    postgres:
      enabled: false