---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externaldns-cloudflare
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: externaldns-cloudflare-secrets
    creationPolicy: Owner
  data:
    - secretKey: cloudflare_api_token
      remoteRef:
        key: Cloudflare
        property: external-dns
