---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-truenas-iscsi
  namespace: democratic-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: truenas
      valuesKey: api-key
      targetPath: driver.config.httpConnection.apiKey
    - kind: Secret
      name: truenas
      valuesKey: ssh-private-key
      targetPath: driver.config.sshConnection.privateKey
  values:
    csiDriver:
      name: "org.democratic-csi.freenas-iscsi"
    storageClasses:
    - name: freenas-iscsi
      defaultClass: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: ext4
        detachedVolumesFromSnapshots: "false"
      mountOptions: []
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:
    driver:
      config:
        driver: freenas-api-iscsi
        httpConnection:
          protocol: https
          host: 172.16.99.10
          port: 443  
          username: truenas_admin
          allowInsecure: true
          apiVersion: 2
        zfs:
          cli:
            sudoEnabled: true
            paths:
              zfs: /usr/sbin/zfs
              zpool: /usr/sbin/zpool
              sudo: /usr/bin/sudo
              chroot: /usr/sbin/chroot
          datasetParentName: kubernetes/iscsi/volumes
          detachedSnapshotsDatasetParentName: kubernetes/iscsi/snapshots
          zvolCompression: 
          zvolDedup:
          zvolEnableReservation: false
          zvolBlocksize:
        iscsi:
          targetPortal: [172.16.99.10:3260]
          targetPortals: []
          interface:
          namePrefix: fsn1-
          nameSuffix: "-talos"
          targetGroups:
            - targetGroupPortalGroup: 1
              targetGroupInitiatorGroup: 1
              targetGroupAuthType: None
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          extentBlocksize: 4096
          extentRpm: "SSD"
          extentAvailThreshold: 0
    node:
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /var/iscsi
        iscsiDirHostPathType: ""
