---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  chart:
    spec:
      chart: flux-operator
      version: 0.32.0
      sourceRef:
        kind: HelmRepository
        name: controlplaneio
        namespace: flux-system
  interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: flux-operator-helm-values
