---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-truenas-iscsi
  namespace: system
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: truenas
      valuesKey: api-key
      targetPath: driver.config.httpConnection.apiKey
    - kind: Secret
      name: truenas
      valuesKey: ssh-private-key
      targetPath: driver.config.sshConnection.privateKey
  values:
    csiDriver:
      name: "org.democratic-csi.iscsi"
    storageClasses:
    - name: truenas-iscsi-nonroot
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: ext4
      mountOptions: []
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:
    driver:
      config:
        driver: freenas-iscsi
        instance_id:
        httpConnection:
          protocol: https
          host: 172.16.99.10
          port: 443
          
          username: truenas_admin
          allowInsecure: true
          apiVersion: 2
        sshConnection:
          host: 172.16.99.10
          port: 22
          username: admin
        zfs:
          cli:
            sudoEnabled: true
            paths:
              zfs: /usr/sbin/zfs
              zpool: /usr/sbin/zpool
              sudo: /usr/bin/sudo
              chroot: /usr/sbin/chroot
          datasetParentName: pool0/csi/vols
          detachedSnapshotsDatasetParentName: pool0/csi/snaps
          zvolCompression: 
          zvolDedup:
          zvolEnableReservation: false
          zvolBlocksize:
        iscsi:
          targetPortal: [172.16.99.10:3260]
          targetPortals: []
          interface:
          namePrefix: fsn1-
          nameSuffix: ""
          targetGroups:
            - targetGroupPortalGroup: 1
              targetGroupInitiatorGroup: 1
              targetGroupAuthType: None
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          extentBlocksize: 4096
          extentRpm: "SSD"
          extentAvailThreshold: 0
