---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumbgppeeringpolicy_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: l3-policy
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  virtualRouters:
    - localASN: 64600
      exportPodCIDR: false
      serviceSelector:
        matchExpressions:
          - key: thisFakeSelector
            operator: NotIn
            values:
              - will-match-and-announce-all-services
      neighbors:
        - peerAddress: 172.16.99.1/32
          peerASN: 65001
