---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hosted
components:
  - ../../components/namespace
resources:
  # - ./authentik/ks.yaml
