---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname cloudflared
  namespace: network
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/main/apps/network/cloudflared/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
