---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-environment
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dex-environment
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: Dex IDP FSN1
        property: client_id
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: Dex IDP FSN1
        property: client_secret
