---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik.yaml
  - cilium.yaml
  - controlplaneio.yaml
  - coredns.yaml
  - democratic-csi.yaml
  - external-secrets.yaml
  - ingress-nginx.yaml
  - jetstack.yaml
  - k8tz.yaml
  - kubernetes-sigs-descheduler.yaml
  - kubernetes-sigs-external-dns.yaml
  - postfinance.yaml
  - prometheus-community.yaml
  - stakater.yaml
